name: turismo_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router:
  cupertino_icons: ^1.0.2

  ## -- Firebase packages
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0

  line_icons: ^2.0.3
  flutter_riverpod: ^2.3.10
  http: ^1.1.0
  intl:
  dash_flags: ^0.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
  - family: Exo
    fonts:
      - asset: assets/fonts/Exo-Bold.ttf
        weight: 700
      - asset: assets/fonts/Exo-Regular.ttf
        weight: 300
      - asset: assets/fonts/Exo-Semibold.ttf
        weight: 600
